version: "3.8"
services:
  postgres-server:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./etc/migration:/docker-entrypoint-initdb.d
    networks:
      - mynet

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres-server
    environment:
      - WAIT_HOSTS=postgres-server:5432
    ports:
      - "8080:8080"
    networks:
      - mynet

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.52.5
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./etc/openapi.yaml:/usr/share/nginx/html/doc/openapi.yaml
    environment:
      BASE_URL: /swagger
      URLS: "[ { url: \"doc/openapi.yaml\", name: \"Secret-Scanner\" } ]"
    networks:
      - mynet

volumes:
  db:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  mynet:
    driver: bridge