openapi: 3.0.3
info:
  title: Secret Scanner
  version: 'v1.0.0'
paths:
  /repositories:
    get:
      summary: get the paginated list of repositories
      operationId: GetRepositories
      description: Retrieve subordinates of specific user by email.
      tags: [ repositories ]
      responses:
        200:
          description: Successful operation. Returns an array of repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
        400:
          $ref: '#/components/responses/BadRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: add a repository
      operationId: AddRepository
      description: Add a repository.
      tags: [ repositories ]
      requestBody:
        description: Repository object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositoryInfo'
      responses:
        201:
          description: Successful operation
        400:
          $ref: '#/components/responses/BadRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /repositories/{repoId}:
    parameters:
    - $ref: '#/components/parameters/idParam'
    get:
      summary: get a repository
      operationId: GetRepositoryByID
      description: Find a specific repository by providing a repoId.
      tags: [ repositories ]
      responses:
        200:
          description: Successful operation. Returns the repository corresponding to the given id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        400:
          $ref: '#/components/responses/BadRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
    patch:
      summary: update a repository
      operationId: UpdateRepository
      description: Update a repository.
      tags: [ repositories ]
      requestBody:
        description: Repository object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositoryInfo'
      responses:
        200:
          description: Successful operation
        400:
          $ref: '#/components/responses/BadRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: delete a repository
      operationId: DeleteRepository
      description: Delete a repository.
      tags: [ repositories ]
      responses:
        200:
          description: Successful operation
        400:
          $ref: '#/components/responses/BadRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /scans:
    get:
      summary: get respositories scanning results
      operationId: GetScanResults
      description: Find repositories scanning results.
      tags: [ repositories ]
      responses:
        200:
          description: Successful operation. Returns all respositories scanning result.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        400:
          $ref: '#/components/responses/BadRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /scans/{repoId}:
    parameters:
    - $ref: '#/components/parameters/idParam'
    post:
      summary: scan a repository
      operationId: ScanRepository
      description: Scan a specific repository by providing a repoId.
      tags: [ repositories ]
      responses:
        200:
          description: Successful operation.
        400:
          $ref: '#/components/responses/BadRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Repository:
      type: object
      required: [ repoId, name, link ]
      properties:
        repoId:
          type: string
        name:
          type: string
        link:
          type: string
    RepositoryInfo:
      type: object
      required: [ name, url ]
      properties:
        name:
          type: string
        url:
          type: string
    Result:
      type: object
      required: [ scanId ]
      properties:
        scanId:
          type: string
        status:
          type: string
          enum: [ Queued, In Progress, Success, Failure ]
        repositoryName:
          type: string
        repositoryUrl:
          type: string
        findings:
          type: array
          items:
            $ref: '#/components/schemas/Finding'
        queuedAt:
          type: string
          format: date
        scanningAt:
          type: string
          format: date
        finishedAt:
          type: string
          format: date
    Finding:
      type: object
      properties:
        type:
          type: string
        ruleId:
          type: string
        location:
          type: object
          properties:
            path:
              type: string
            positions:
              type: object
              properties:
                begin:
                  type: object
                  properties:
                    line:
                      type: integer
                      format: int32
        metadata:
          type: object
          properties:
            description:
              type: string
            severity:
              type: string
  parameters:
    idParam:
      name: repoId
      in: path
      description: Repository id.
      required: true
      schema:
        type: string
  responses:
    BadRequestError:
      description: Invalid request message parameters
    InternalServerError:
      description: Internal server error
